ProgrammeVitam/vitam-doc

- source/index.rst
- source/sections/Vademecum_arbre.md
- source/sections/Vademecum_contrat_gestion.md
- source/sections/Vademecum_eliminations.md
- source/sections/Vademecum_glossaire.md
- source/sections/Vademecum_parametrages_pf.md
- source/sections/Vademecum_plan.md
- source/sections/Vademecum_registre_fonds.md
> vademecum_lot1

- source/index.rst
- source/sections/Vademecum_audit.md
- source/sections/Vademecum_classification.md
- source/sections/Vademecum_contrat_acces.md
- source/sections/Vademecum_contrat_entree.md
- source/sections/Vademecum_echeances.md
- source/sections/Vademecum_glossaire.md
- source/sections/Vademecum_habilitations.md
- source/sections/Vademecum_identifiants.md
- source/sections/Vademecum_journalisation.md
- source/sections/Vademecum_ontologie.md
- source/sections/Vademecum_pa.md
- source/sections/Vademecum_preservation.md
- source/sections/Vademecum_sommaire.md
- source/sections/Vademecum_suivi_acces.md
> vademecum lot2

- source/sections/services_prod.md
> MAJ_doc_services-producteurs_cible-V7.0

- source/sections/eliminations.md
Configuration du rapport d'élimination
> MAJ_doc_elimination_cible-V7.0

- source/sections/modele_de_workflow.md
ajout d'un cas 14 : check_dataobjectpackage
> MAJ_doc_workflow_cible-V7.0

- source/sections/Vademecum_contrat_entree.md
- source/sections/modele_de_donnees.md
Maj MDD et Maj fiche vademecum contrat d'entrée
> Story 11585 suite

- source/sections/modele_de_donnees.md
- source/sections/module_de_collecte.md
ajout du champ AutomaticIngest dans le modèle de données et dans la doc module de collecte
> US_12063 : Première version de l’automate gérant l’envoi des SIP de Collecte vers Vitam

- source/sections/gestion_archives_arbo.md
- source/sections/gestion_habilitations.md
recherche via les identifiants pérennes
> US_10305 : recherche via identifiant pérenne

- source/sections/modele_de_workflow.md
- source/sections/preservation.md
- source/sections/valeur_probante.md
Ajout du paramètre includeDetachedSigningInformation dans le relevé de valeur probante
> Story #11982: Ajout du paramètre includeDetachedSigningInformation dans le relevé de valeur probante

- source/sections/modele_de_donnees.md
Documentation of data model : 
> Report :
* BulkUpdateUnitMetadataReport
* DeleteGotVersionsReport
* EvidenceAuditReport
* ExtractedMetadata
* InvalidUnits
* PurgeObjectGroup
* PurgeUnit
* TraceabilityReport
* TransferReplyUnit
* UpdateUnitReport
>  Metadata
PurgedPersistentIdentifier
> Masterdata
ontologie : StringSize + TypeDetail 
> Masterdata 
schema
> Collect 
Transaction : Batches, batchId, _batchStatus, AutomaticIngest 
Project : AutomaticIngest
>  MetadataCollect
Unit : Batches, batchId, _batchStatus
> Story #12274 : update data model documentation

- source/index.rst
- source/sections/gestion_archives_arbo.md
- source/sections/guide_lecture.md
- source/sections/guide_prise_en_main.md
- source/sections/modele_de_donnees.md
- source/sections/module_de_collecte.md
- source/sections/ontologie.md
- source/sections/organisation_information.md
- source/sections/presentation_programme.md
- source/sections/preservation.md
- source/sections/profil_archivage.md
- source/sections/profil_unite_archivistique.md
- source/sections/regles_gestion.md
- source/sections/services_prod.md
- source/sections/stockage.md
- source/sections/transfert.md
- source/sections/valeur_probante.md
Organisation de l'information en nouvelle doc
corrections sur de nombreux fichiers de doc
> Nouvelle doc et corrections

- source/sections/chantier_identification_format.md
- source/sections/chantier_preservation_validation_format.md
- source/sections/modele_de_donnees.md
- source/sections/resip.md
- source/sections/resip_faq.md
- source/sections/valeur_probante.md
chantiers : liens hypertextes avec parenthèses ou <>
ReSIP essai sur les liens internes avec un seul mot entre []
> Corrections_doc

- source/sections/transfert.md
ajout d'un retour erreur lors de l'export du DIP de transfert
> doc design SIP 7.1

- source/sections/gestion_habilitations.md
US_12141 ajout EndPoint mise à jour unitaire en masse des md dans le module de collecte
> Habilitations V.7.1

- source/sections/eliminations.md
- source/sections/gel.md
- source/sections/gestion_archives_arbo.md
- source/sections/ontologie.md
- source/sections/profil_unite_archivistique.md
Doc éliminations, gel, arbo, ontologie, PUA
> Corrections

- source/sections/resip.md
> V8 MAJ - RESIP

- source/sections/eliminations.md
version du SEDA 2.3, enregistrement des ID pérennes (fonctionnalité V7.1)
> MAJ V8 - élimination

- source/sections/resip_faq.md
> MAJ V8 - resip FAQ

- source/sections/valeur_probante.md
corrections de coquilles, ajout du paramètre sur les doc signés dans le relevé de valeur probante.
> MAJ V8 - relevé de valeur probante

- source/sections/guide_prise_en_main.md
maj version du SEDA et version de la release
raf : notes de bas de page à rétablir.
> MAJ V.8 guide de prise en main

- source/sections/profil_archivage.md
US12814 : publication du SEDA 2.3, prise en compte du SEDA 2.2 et 2.3 dans Pastis, déclaration de la version du SEDA dans le référentiel
> V8 profil d'archivage

- source/sections/modele_de_donnees.md
Ajout de la documentation sur le modèle de données des services agents
> Story #13338: add data model doc for agencies

- source/sections/Vademecum_referentiel_sa.md
maj du référentiel des services producteurs
> V8_vademecum_sa

- source/sections/profil_unite_archivistique.md
Gestion de la version du SEDA 2.2 et 2.3, accès au schéma via un PUA.
> US 13279 et sq

- source/sections/gestion_archives_arbo.md
personnalisation des ATR et des rapports d'élimination
> V8_gestion des arbo_2

- source/index.rst
- source/sections/pastis_standalone.md
Initialisation de la documentation pour Pastis standalone, avec notamment la documentation de l'extension des métadonnées descriptives.
Il reste des informations à ajouter.
> Story #13923: Pastis standalone documentation

- source/sections/pastis_standalone.md
> V8.1_pastis

- source/sections/eliminations.md
distinction front entre suppression d'arbres et élimination d'archives et de plan de classement.
> MAJ_V8.1_éliminations

- source/sections/organisation_information.md
> MAJ_V8.1_organisation de l'information

- source/sections/profil_unite_archivistique.md
Mise à jour d'un PUA depuis le front office, ajout du bloc facettes, autres modifications
> MAJ_V8.1_pua

- source/sections/profil_archivage.md
ajout d'une partie sur l'accès au référentiel + partie sur la gestion des extensions
> MAJ_V8.1_profils

- source/sections/ontologie.md
ajout d'une partie "accès au référentiel" et correction de qq coquilles
> MAJ_8.1_ontologie

- source/sections/gel.md
pas de maj fonctionnelle, qq corrections marginales
> MAJ_8.1__gel
